client_config_backend: file
client_config:
    client_id: 929534751155-m9c9f9s8qjr4fvjoptslnnbkdj91emd2.apps.googleusercontent.com
    client_secret: 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

save_credentials: True  
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive