# Generated by Django 4.1.8 on 2023-04-12 10:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=20)),
                ('roll_no', models.CharField(default='None', max_length=13, unique=True)),
                ('email', models.CharField(default='None', max_length=200, unique=True)),
                ('password', models.CharField(default='eQfZkta', max_length=20)),
                ('user_type', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], default='student', max_length=7)),
                ('fathers_name', models.CharField(blank=True, default='', max_length=20)),
                ('mothers_name', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('session', models.CharField(default='', max_length=10)),
                ('college_Name', models.CharField(default='', max_length=100)),
                ('course_name', models.CharField(default='', max_length=20)),
                ('branch', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, default='false', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=api.models.name_image)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=20)),
                ('email', models.CharField(default='None', max_length=200, unique=True)),
                ('password', models.CharField(default='Ll0x2Om', max_length=20)),
                ('user_type', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], default='teacher', max_length=7)),
                ('fathers_name', models.CharField(blank=True, default='', max_length=20)),
                ('mothers_name', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('college_Name', models.CharField(default='', max_length=100)),
                ('course_name', models.CharField(default='', max_length=20)),
                ('branch', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, default='false', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=api.models.name_image)),
            ],
        ),
    ]
