# Generated by Django 4.1.8 on 2023-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_models_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='tNdh2HT', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='EdMBaHW', max_length=20),
        ),
    ]
