# Generated by Django 4.1.8 on 2023-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_models_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='BIZTEJ7', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='IQ2Ysi3', max_length=20),
        ),
    ]
