# Generated by Django 3.2.12 on 2023-04-21 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_student_models_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=api.models.name_profile_image),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=api.models.name_profile_image),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='In9B2Sg', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='v9hjzL5', max_length=20),
        ),
    ]
