# Generated by Django 3.2.12 on 2023-04-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230423_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='htoWwjM', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='RpClGUu', max_length=20),
        ),
    ]
