# Generated by Django 3.2.12 on 2023-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230423_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_models',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teacher_models',
            name='status',
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='6WFZznH', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='xtYvS09', max_length=20),
        ),
    ]
