# Generated by Django 3.2.12 on 2023-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230423_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='sUlh28n', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='kNoAfeS', max_length=20),
        ),
    ]
