# Generated by Django 3.2.12 on 2023-04-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230423_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='IMxDun8', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='SGB6lLH', max_length=20),
        ),
    ]
