# Generated by Django 3.2.12 on 2023-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230423_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='nrfE0eU', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='9cAS1aN', max_length=20),
        ),
    ]
