# Generated by Django 3.2.12 on 2023-04-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230423_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='20M8xrW', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='DSTqdty', max_length=20),
        ),
    ]
