# Generated by Django 3.2.12 on 2023-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230423_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='social_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='social_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='specialized_in',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='subjects',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='fTi7pJV', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='OVYhwUD', max_length=20),
        ),
    ]
