# Generated by Django 4.1.8 on 2023-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230423_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_models',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='gOlaI15', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='5vj3DuV', max_length=20),
        ),
    ]
