# Generated by Django 4.1.8 on 2023-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_student_models_year_alter_student_models_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_models',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='teacher_models',
            name='mothers_name',
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_models',
            name='password',
            field=models.CharField(default='FGJDKZP', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_models',
            name='password',
            field=models.CharField(default='GD5u3WL', max_length=20),
        ),
    ]
